version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 9000:9000
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3307/demo_test?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mariadb

    volumes:
      - .m2:/root/.m2

  mariadb:
    image: "mariadb"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: demo_test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
networks:
  springapimysql-net:
